# Generated by Django 3.2.3 on 2023-10-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_label', '0001_initial'),
        ('ingredients_label', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientquantity',
            name='ingredient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ingredients_label.ingredient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipes_label.recipe'),
            preserve_default=False,
        ),
    ]
