# Generated by Django 3.2.3 on 2023-10-16 21:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_label', '0004_alter_recipe_name'),
        ('ingredients_label', '0002_auto_20231014_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ingredientquantity',
            options={'ordering': ['ingredient']},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.TextField(verbose_name='Единица'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32000)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients_label.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes_label.recipe', verbose_name='Рецепт'),
        ),
    ]
