# Generated by Django 3.2.3 on 2023-10-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_label', '0003_auto_20231016_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientquantity',
            name='measurement_unit',
            field=models.ManyToManyField(related_name='_ingredients_label_ingredientquantity_measurement_unit_+', through='ingredients_label.Ingredient', to='ingredients_label.IngredientQuantity'),
        ),
    ]
