# Generated by Django 3.2.3 on 2023-10-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_label', '0004_ingredientquantity_measurement_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.ManyToManyField(related_name='_ingredients_label_ingredient_amount_+', through='ingredients_label.IngredientQuantity', to='ingredients_label.Ingredient'),
        ),
    ]
