# Generated by Django 3.2.3 on 2023-10-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_label', '0005_ingredient_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredientquantity',
            name='measurement_unit',
        ),
    ]
