# Generated by Django 3.2.3 on 2023-10-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients_label', '0007_ingredientquantity_unique_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_quantities', to='ingredients_label.ingredient', verbose_name='Ингредиент'),
        ),
    ]
