# Generated by Django 3.2.3 on 2023-11-08 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_label', '0007_recipe_tags'),
        ('ingredients_label', '0009_auto_20231019_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='recipe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_amount', to='recipes_label.recipe', verbose_name='Рецепт'),
        ),
    ]
