# Generated by Django 3.2.3 on 2023-10-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags_label', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_label_taggedrecipe_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_label_taggedrecipe_items', to='tags_label.customtag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
