# Generated by Django 3.2.3 on 2023-10-17 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_label', '0002_taggedrecipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customtag',
            options={'ordering': ['color'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='taggedrecipe',
            options={'ordering': ['tag']},
        ),
        migrations.AlterField(
            model_name='customtag',
            name='color',
            field=models.TextField(verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='taggedrecipe',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_label_taggedrecipe_items', to='tags_label.customtag', verbose_name='Таг'),
        ),
    ]
