# Generated by Django 3.2.3 on 2023-10-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags_label', '0002_taggedrecipe'),
        ('recipes_label', '0002_auto_20231014_1143'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='recipe',
    #         name='tags',
    #         field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tags_label.TaggedRecipe', to='tags_label.CustomTag', verbose_name='Tags'),
    #     ),
    # ]
