# Generated by Django 3.2.3 on 2023-10-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_label', '0003_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.TextField(),
        ),
    ]
