# Generated by Django 3.2.3 on 2023-10-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags_label', '0004_auto_20231020_1511'),
        ('recipes_label', '0006_auto_20231017_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='tags_label.Tag', verbose_name='Таги'),
        ),
    ]
