# Generated by Django 3.2.3 on 2023-10-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_label', '0002_auto_20231014_1143'),
        ('users_label', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_recipes',
            field=models.ManyToManyField(related_name='favorited_by', to='recipes_label.Recipe'),
        ),
        migrations.AddField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(related_name='in_shopping_cart', to='recipes_label.Recipe'),
        ),
    ]
