# Generated by Django 3.2.3 on 2023-10-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_label', '0002_auto_20231014_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
    ]
